# Environment variables
MYSQL_USERNAME: admin
MYSQL_PASSWORD: takemyhand
MYSQL_PASSWORD_ROOT: letmein
MYSQL_HOST: 127.0.0.1
MYSQL_PORT: 3305
MYSQL_DATABASE: mysourcedb

CONTAINER_PORT: 8085
HOST_PORT: 8080
ACTIVE_PROFILE: dev

EMAIL_HOST: smtp.gmail.com
EMAIL_PORT: 587
EMAIL_ID: <your-email>
EMAIL_PASSWORD: <your-password>
VERIFY_EMAIL_HOST: http://localhost:${CONTAINER_PORT}

UI_APP_URL: http://localhost:4200
