# Environment variables
MYSQL_USERNAME: admin
MYSQL_PASSWORD: takemyhand
MYSQL_PASSWORD_ROOT: letmein
MYSQL_HOST: 127.0.0.1
MYSQL_PORT: 3305
MYSQL_DATABASE: mysourcedb

CONTAINER_PORT: 8085
ACTIVE_PROFILE: dev

EMAIL_HOST: smtp.gmail.com
EMAIL_PORT: 587
EMAIL_ID: ecosystemprogramminglanguage@gmail.com
EMAIL_PASSWORD: ainubmlhyfkrbnzy
VERIFY_EMAIL_HOST: http://localhost:${CONTAINER_PORT}

JWT_EXPIRATION: 432_000_000
JWT_SECRET: ${SECRET}

UI_APP_URL: http://localhost:4200
